// Code Generator — produces registry-grade .tsx files from component state + edits
// Supports both editing existing components and generating new ones from scratch.

import type { CustomVariantDef } from "@/lib/component-state"
import type {
  ComponentTree,
  ElementNode,
  ComponentProp,
  SubComponentDef,
} from "@/lib/component-tree"

/* ── Public types ──────────────────────────────────────────────── */

export interface GenerateOptions {
  /** Component identity */
  componentName: string // e.g. "MyButton"
  slug: string // e.g. "my-button"

  /** Base — existing source to modify (edit mode) */
  originalSource?: string

  /** From-scratch options */
  baseElement?: string // e.g. "button", "div", "input"

  /** User edits */
  customClasses: Record<string, string[]> // per-element custom classes
  customVariantDefs: CustomVariantDef[] // user-created variants
  activeSubComponents: string[] // which sub-components are active

  /** Options */
  enableAsChild?: boolean // whether to add Slot support
  enableForwardRef?: boolean // whether to use forwardRef (default true)
}

/* ── Element type mapping ──────────────────────────────────────── */

interface ElementTypeInfo {
  htmlElement: string
  htmlAttributes: string
}

const ELEMENT_TYPE_MAP: Record<string, ElementTypeInfo> = {
  button: {
    htmlElement: "HTMLButtonElement",
    htmlAttributes: "React.ButtonHTMLAttributes<HTMLButtonElement>",
  },
  div: {
    htmlElement: "HTMLDivElement",
    htmlAttributes: "React.HTMLAttributes<HTMLDivElement>",
  },
  input: {
    htmlElement: "HTMLInputElement",
    htmlAttributes: "React.InputHTMLAttributes<HTMLInputElement>",
  },
  a: {
    htmlElement: "HTMLAnchorElement",
    htmlAttributes: "React.AnchorHTMLAttributes<HTMLAnchorElement>",
  },
  span: {
    htmlElement: "HTMLSpanElement",
    htmlAttributes: "React.HTMLAttributes<HTMLSpanElement>",
  },
  form: {
    htmlElement: "HTMLFormElement",
    htmlAttributes: "React.FormHTMLAttributes<HTMLFormElement>",
  },
  img: {
    htmlElement: "HTMLImageElement",
    htmlAttributes: "React.ImgHTMLAttributes<HTMLImageElement>",
  },
  textarea: {
    htmlElement: "HTMLTextAreaElement",
    htmlAttributes: "React.TextareaHTMLAttributes<HTMLTextAreaElement>",
  },
  select: {
    htmlElement: "HTMLSelectElement",
    htmlAttributes: "React.SelectHTMLAttributes<HTMLSelectElement>",
  },
}

/**
 * Returns the element type info for a given base element tag.
 * Falls back to div if the element is not in the map.
 */
function getElementTypeInfo(element: string): ElementTypeInfo {
  // PascalCase = shadcn component wrapper
  if (/^[A-Z]/.test(element)) {
    return {
      htmlElement: `React.ElementRef<typeof ${element}>`,
      htmlAttributes: `React.ComponentPropsWithoutRef<typeof ${element}>`,
    }
  }
  return (
    ELEMENT_TYPE_MAP[element] ?? {
      htmlElement: "HTMLDivElement",
      htmlAttributes: "React.HTMLAttributes<HTMLDivElement>",
    }
  )
}

/* ── Name utilities ────────────────────────────────────────────── */

/**
 * Converts a kebab-case or space-separated string to PascalCase.
 * e.g. "my-button" -> "MyButton", "alert dialog" -> "AlertDialog"
 */
export function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, char: string | undefined) =>
      char ? char.toUpperCase() : "",
    )
    .replace(/^(.)/, (_, char: string) => char.toUpperCase())
}

/**
 * Converts a kebab-case or space-separated string to camelCase.
 * e.g. "my-button" -> "myButton", "alert dialog" -> "alertDialog"
 */
export function toCamelCase(str: string): string {
  const pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/* ── Main generators ───────────────────────────────────────────── */

/**
 * Entry point: routes to edit mode or from-scratch based on whether
 * originalSource is provided.
 */
export function generateComponentCode(options: GenerateOptions): string {
  if (options.originalSource) {
    return generateFromExisting(options)
  }
  return generateFromScratch(options)
}

/* ── Edit mode: modify existing source ─────────────────────────── */

/**
 * Takes an existing component source and injects user edits:
 * - Custom classes into cva base / cn() / className
 * - Custom variant definitions into cva variants block
 * - Sub-component removal via comment markers
 * - Header comment with generation info
 */
function generateFromExisting(options: GenerateOptions): string {
  const {
    originalSource,
    customClasses,
    customVariantDefs,
    componentName,
  } = options

  if (!originalSource) return ""

  const hasCustomClasses = Object.values(customClasses).some(
    (classes) => classes.length > 0,
  )
  const hasCustomVariants = customVariantDefs.length > 0
  const isUnmodified = !hasCustomClasses && !hasCustomVariants

  const header = `// Generated by shadcn Playground\n// Component: ${componentName}\n\n`

  if (isUnmodified) {
    return header + originalSource
  }

  let output = originalSource

  // Inject custom classes into the root className / cva base
  if (hasCustomClasses) {
    output = injectCustomClasses(output, customClasses)
  }

  // Inject custom variant definitions into cva variants block
  if (hasCustomVariants) {
    output = injectCustomVariants(output, customVariantDefs)
  }

  return header + output
}

/* ── From-scratch generation ───────────────────────────────────── */

/**
 * Generates a complete component file from scratch following shadcn conventions:
 * - forwardRef wrapping (configurable)
 * - cva for variants (when variant defs exist)
 * - cn() for class merging
 * - Slot/asChild support (configurable)
 * - Proper TypeScript interfaces extending HTML element types
 * - Named exports with displayName
 */
export function generateFromScratch(options: GenerateOptions): string {
  const {
    componentName,
    slug,
    baseElement = "div",
    customClasses,
    customVariantDefs,
    enableAsChild = false,
    enableForwardRef = true,
  } = options

  const name = toPascalCase(componentName)
  const variantsName = `${toCamelCase(componentName)}Variants`
  const elementInfo = getElementTypeInfo(baseElement)
  const hasVariants = customVariantDefs.length > 0
  const rootClasses = customClasses["root"] ?? []

  // ── Build imports ──────────────────────────────────────────────
  const imports = buildImports({ enableAsChild, hasVariants })

  // ── Build cva call (if variants exist) ─────────────────────────
  const cvaBlock = hasVariants
    ? buildCvaBlock(variantsName, rootClasses, customVariantDefs)
    : ""

  // ── Build interface ────────────────────────────────────────────
  const interfaceBlock = buildInterface({
    name,
    variantsName,
    elementInfo,
    hasVariants,
    enableAsChild,
  })

  // ── Build component ────────────────────────────────────────────
  const componentBlock = enableForwardRef
    ? buildForwardRefComponent({
        name,
        variantsName,
        baseElement,
        elementInfo,
        rootClasses,
        customVariantDefs,
        hasVariants,
        enableAsChild,
      })
    : buildFunctionComponent({
        name,
        variantsName,
        baseElement,
        rootClasses,
        customVariantDefs,
        hasVariants,
        enableAsChild,
      })

  // ── Build exports ──────────────────────────────────────────────
  const exportsBlock = hasVariants
    ? `export { ${name}, ${variantsName} }`
    : `export { ${name} }`

  // ── Assemble ───────────────────────────────────────────────────
  const sections = [
    "// Generated by shadcn Playground",
    "",
    imports,
    "",
    ...(cvaBlock ? [cvaBlock, ""] : []),
    interfaceBlock,
    "",
    componentBlock,
    `${name}.displayName = "${name}"`,
    "",
    exportsBlock,
    "",
  ]

  return sections.join("\n")
}

/* ── Import builder ────────────────────────────────────────────── */

function buildImports(opts: {
  enableAsChild: boolean
  hasVariants: boolean
}): string {
  const lines: string[] = ['import * as React from "react"']

  if (opts.enableAsChild) {
    lines.push('import { Slot } from "@radix-ui/react-slot"')
  }

  if (opts.hasVariants) {
    lines.push(
      'import { cva, type VariantProps } from "class-variance-authority"',
    )
  }

  lines.push("")
  lines.push('import { cn } from "@/lib/utils"')

  return lines.join("\n")
}

/* ── CVA block builder ─────────────────────────────────────────── */

function buildCvaBlock(
  variantsName: string,
  rootClasses: string[],
  customVariantDefs: CustomVariantDef[],
): string {
  const baseClasses = rootClasses.length > 0 ? rootClasses.join(" ") : ""

  const variantGroups = customVariantDefs
    .filter((def) => def.type === "variant")
    .map((def) => {
      const optionEntries = def.options
        .map((opt) => `        ${opt}: "",`)
        .join("\n")
      return `      ${def.name}: {\n${optionEntries}\n      },`
    })

  const booleanGroups = customVariantDefs
    .filter((def) => def.type === "boolean")
    .map((def) => {
      return `      ${def.name}: {\n        true: "",\n        false: "",\n      },`
    })

  const allGroups = [...variantGroups, ...booleanGroups].join("\n")

  const defaultEntries = customVariantDefs
    .map((def) => {
      const val = def.type === "boolean" ? "false" : def.defaultValue
      return `      ${def.name}: "${val}",`
    })
    .join("\n")

  return `const ${variantsName} = cva(
  "${baseClasses}",
  {
    variants: {
${allGroups}
    },
    defaultVariants: {
${defaultEntries}
    },
  }
)`
}

/* ── Interface builder ─────────────────────────────────────────── */

function buildInterface(opts: {
  name: string
  variantsName: string
  elementInfo: ElementTypeInfo
  hasVariants: boolean
  enableAsChild: boolean
}): string {
  const extensions = [opts.elementInfo.htmlAttributes]
  if (opts.hasVariants) {
    extensions.push(`VariantProps<typeof ${opts.variantsName}>`)
  }

  const extendClause = extensions
    .map((ext, i) => (i === 0 ? `  extends ${ext}` : `    ${ext}`))
    .join(",\n")

  const asChildProp = opts.enableAsChild ? "\n  asChild?: boolean" : ""

  return `export interface ${opts.name}Props
${extendClause} {${asChildProp}
}`
}

/* ── forwardRef component builder ──────────────────────────────── */

function buildForwardRefComponent(opts: {
  name: string
  variantsName: string
  baseElement: string
  elementInfo: ElementTypeInfo
  rootClasses: string[]
  customVariantDefs: CustomVariantDef[]
  hasVariants: boolean
  enableAsChild: boolean
}): string {
  const variantPropNames = opts.customVariantDefs.map((def) => def.name)
  const destructured = buildDestructuredProps(
    variantPropNames,
    opts.enableAsChild,
  )
  const classNameExpr = buildClassNameExpr(opts)
  const compExpr = opts.enableAsChild
    ? `    const Comp = asChild ? Slot : "${opts.baseElement}"\n`
    : ""
  const tag = opts.enableAsChild ? "Comp" : `"${opts.baseElement}"`

  return `const ${opts.name} = React.forwardRef<${opts.elementInfo.htmlElement}, ${opts.name}Props>(
  (${destructured}, ref) => {
${compExpr}    return (
      <${tag === `"${opts.baseElement}"` ? opts.baseElement : "Comp"}
        className={${classNameExpr}}
        ref={ref}
        {...props}
      />
    )
  }
)`
}

/* ── Function component builder (no forwardRef) ────────────────── */

function buildFunctionComponent(opts: {
  name: string
  variantsName: string
  baseElement: string
  rootClasses: string[]
  customVariantDefs: CustomVariantDef[]
  hasVariants: boolean
  enableAsChild: boolean
}): string {
  const variantPropNames = opts.customVariantDefs.map((def) => def.name)
  const destructured = buildDestructuredProps(
    variantPropNames,
    opts.enableAsChild,
  )
  const classNameExpr = buildClassNameExpr(opts)
  const compExpr = opts.enableAsChild
    ? `  const Comp = asChild ? Slot : "${opts.baseElement}"\n`
    : ""
  const tag = opts.enableAsChild ? "Comp" : opts.baseElement

  return `function ${opts.name}(${destructured}) {
${compExpr}  return (
    <${tag}
      className={${classNameExpr}}
      {...props}
    />
  )
}`
}

/* ── Shared component helpers ──────────────────────────────────── */

/**
 * Builds the destructured props string for the component function.
 * e.g. "{ className, variant, size, asChild = false, ...props }"
 */
function buildDestructuredProps(
  variantPropNames: string[],
  enableAsChild: boolean,
): string {
  const parts: string[] = ["className"]
  parts.push(...variantPropNames)
  if (enableAsChild) {
    parts.push("asChild = false")
  }
  parts.push("...props")
  return `{ ${parts.join(", ")} }`
}

/**
 * Builds the className expression for JSX.
 * Uses cva + cn when variants exist, or plain cn otherwise.
 */
function buildClassNameExpr(opts: {
  variantsName: string
  rootClasses: string[]
  customVariantDefs: CustomVariantDef[]
  hasVariants: boolean
}): string {
  if (opts.hasVariants) {
    const variantArgs = opts.customVariantDefs
      .map((def) => def.name)
      .join(", ")
    return `cn(${opts.variantsName}({ ${variantArgs}, className }))`
  }

  // No variants — use cn with base classes
  if (opts.rootClasses.length > 0) {
    return `cn("${opts.rootClasses.join(" ")}", className)`
  }

  return `cn(className)`
}

/* ── Class injection (edit mode) ───────────────────────────────── */

/**
 * Injects custom classes into the component source. For "root" classes,
 * appends them to the first cva() base string, cn() call, or className.
 */
function injectCustomClasses(
  source: string,
  customClasses: Record<string, string[]>,
): string {
  let output = source

  const rootClasses = customClasses["root"]
  if (rootClasses && rootClasses.length > 0) {
    const classString = rootClasses.join(" ")

    // Strategy 1: Inject into cva() base string — cva("existing-classes",
    const cvaBaseMatch = /cva\(\s*"([^"]*)"/.exec(output)
    if (cvaBaseMatch) {
      const existingBase = cvaBaseMatch[1]
      const newBase = existingBase
        ? `${existingBase} ${classString}`
        : classString
      output = output.replace(
        `cva("${existingBase}"`,
        `cva("${newBase}"`,
      )
      return output
    }

    // Strategy 2: Inject into the first cn() call inside a className
    const cnMatch = /className=\{cn\(\s*"([^"]*)"/.exec(output)
    if (cnMatch) {
      const existingCn = cnMatch[1]
      const newCn = existingCn
        ? `${existingCn} ${classString}`
        : classString
      output = output.replace(
        `className={cn("${existingCn}"`,
        `className={cn("${newCn}"`,
      )
      return output
    }

    // Strategy 3: Wrap a plain className in cn() with the new classes
    const classNameMatch = /className="([^"]*)"/.exec(output)
    if (classNameMatch) {
      const existingClass = classNameMatch[1]
      output = output.replace(
        `className="${existingClass}"`,
        `className={cn("${existingClass} ${classString}")}`,
      )
    }
  }

  return output
}

/* ── Variant injection (edit mode) ─────────────────────────────── */

/**
 * Injects custom variant definitions into the cva() variants block.
 */
function injectCustomVariants(
  source: string,
  customVariantDefs: CustomVariantDef[],
): string {
  let output = source

  const variantsBlockEnd = findVariantsBlockEnd(output)
  if (variantsBlockEnd === -1) {
    return injectVariantsBlock(output, customVariantDefs)
  }

  const variantEntries = customVariantDefs
    .map((def) => formatVariantEntry(def))
    .join("")

  output =
    output.slice(0, variantsBlockEnd) +
    variantEntries +
    output.slice(variantsBlockEnd)

  output = injectDefaultVariants(output, customVariantDefs)

  return output
}

/**
 * Finds the position just before the closing `}` of the `variants: { ... }`
 * block inside cva(). Returns -1 if not found.
 */
function findVariantsBlockEnd(source: string): number {
  const pattern = /variants\s*:\s*\{/
  const match = pattern.exec(source)
  if (!match) return -1

  const startIndex = match.index + match[0].length
  let depth = 1
  let i = startIndex

  while (i < source.length && depth > 0) {
    const char = source[i]
    if (char === "{") depth++
    else if (char === "}") depth--

    if (depth === 0) return i

    if (char === '"' || char === "'" || char === "`") {
      i = skipString(source, i, char)
      continue
    }

    i++
  }

  return -1
}

/**
 * Creates a full variants block inside an existing cva() call that
 * doesn't have one yet.
 */
function injectVariantsBlock(
  source: string,
  defs: CustomVariantDef[],
): string {
  const cvaMatch = /cva\(\s*"[^"]*"\s*,\s*\{/.exec(source)
  if (!cvaMatch) return source

  const insertPos = cvaMatch.index + cvaMatch[0].length
  const variantEntries = defs.map((def) => formatVariantEntry(def)).join("")

  const variantsBlock = `\n    variants: {${variantEntries}\n    },`

  return (
    source.slice(0, insertPos) + variantsBlock + source.slice(insertPos)
  )
}

/**
 * Injects default values for custom variants into the defaultVariants block.
 */
function injectDefaultVariants(
  source: string,
  defs: CustomVariantDef[],
): string {
  const defaultsPattern = /defaultVariants\s*:\s*\{/
  const match = defaultsPattern.exec(source)
  if (!match) return source

  const insertPos = match.index + match[0].length
  const defaults = defs
    .map((def) => `\n      ${def.name}: "${def.defaultValue}",`)
    .join("")

  return source.slice(0, insertPos) + defaults + source.slice(insertPos)
}

/**
 * Formats a single custom variant definition as a cva variants entry.
 */
function formatVariantEntry(def: CustomVariantDef): string {
  if (def.type === "boolean") {
    return `\n      ${def.name}: {\n        true: "",\n        false: "",\n      },`
  }

  const optionEntries = def.options
    .map((opt) => `\n          ${opt}: "",`)
    .join("")

  return `\n      ${def.name}: {${optionEntries}\n      },`
}

/* ── Tree-based generation ─────────────────────────────────────── */

/**
 * Generates a complete .tsx file from a ComponentTree.
 * Includes the main component, all sub-components, props interface,
 * cva variants, and proper imports.
 */
export function generateFromTree(tree: ComponentTree): string {
  const { name, baseElement, variants, props, subComponents } = tree
  const hasVariants = variants.length > 0
  const hasProps = props.length > 0
  const hasSubComponents = subComponents.length > 0
  const hasReactNode = props.some((p) => p.type === "ReactNode")
  const elementInfo = getElementTypeInfo(baseElement)
  const variantsName = `${toCamelCase(name)}Variants`

  const sections: string[] = []

  // ── Imports ──────────────────────────────────────────────────────
  const importLines: string[] = ['import * as React from "react"']
  importLines.push("")
  importLines.push('import { cn } from "@/lib/utils"')

  // Add imports for shadcn base components used by this component or its sub-components
  const shadcnBases = new Set<string>()
  if (/^[A-Z]/.test(tree.baseElement)) shadcnBases.add(tree.baseElement)
  for (const sc of tree.subComponents) {
    if (/^[A-Z]/.test(sc.baseElement)) shadcnBases.add(sc.baseElement)
  }
  for (const scName of shadcnBases) {
    const slug = scName.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()
    importLines.push(`import { ${scName} } from "@/components/ui/${slug}"`)
  }

  sections.push(importLines.join("\n"))

  // ── Inline type for variant + custom props ─────────────────────
  const extraProps: string[] = []
  for (const v of variants) {
    const unionType = v.type === "boolean"
      ? "boolean"
      : v.options.map((o) => `"${o}"`).join(" | ")
    extraProps.push(`${v.name}?: ${unionType}`)
  }
  for (const prop of props) {
    const tsType = propTypeToTs(prop.type, hasReactNode)
    const optional = prop.required ? "" : "?"
    extraProps.push(`${prop.name}${optional}: ${tsType}`)
  }

  const typeAnnotation = extraProps.length > 0
    ? `React.ComponentProps<"${tree.baseElement}"> & { ${extraProps.join("; ")} }`
    : `React.ComponentProps<"${tree.baseElement}">`

  // ── Main component (plain function, modern shadcn style) ──────
  const namedProps = [
    "className",
    ...variants.map((v) => {
      const def = v.defaultValue
      if (v.type === "boolean") return `${v.name} = ${def === "true" ? "true" : "false"}`
      return def ? `${v.name} = "${def}"` : v.name
    }),
    ...props.map((p) => {
      if (p.defaultValue !== undefined && p.defaultValue !== "") {
        return `${p.name} = ${formatDefaultValue(p)}`
      }
      return p.name
    }),
  ]

  const userClasses = (tree.classes ?? []).join(" ")

  // Add group/name class for Tailwind group targeting by children
  const kebabName = name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()
  const groupClass = hasSubComponents ? `group/${kebabName}` : ""
  const allBaseClasses = [groupClass, userClasses].filter(Boolean).join(" ")

  const classNameExpr = allBaseClasses
    ? `cn("${allBaseClasses}", className)`
    : "className"

  // Build data-* attributes for each variant prop
  const dataAttrs = variants.map((v) => {
    const kebab = v.name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()
    return `data-${kebab}={${v.name}}`
  })

  const attrLines = [
    tree.dataSlot ? `data-slot="${tree.dataSlot}"` : "",
    ...dataAttrs,
    `className={${classNameExpr}}`,
    "{...props}",
  ].filter(Boolean)

  const destructuredStr = namedProps.length > 0
    ? `${namedProps.join(",\n  ")},\n  ...props`
    : "...props"

  sections.push(
    `function ${name}({
  ${destructuredStr}
}: ${typeAnnotation}) {
  return (
    <${tree.baseElement}
      ${attrLines.join("\n      ")}
    />
  )
}`,
  )

  // ── Sub-components ───────────────────────────────────────────────
  if (hasSubComponents) {
    for (const sub of subComponents) {
      sections.push(generateSubComponent(sub, name))
    }
  }

  // ── Exports ──────────────────────────────────────────────────────
  const exportNames = [name]
  for (const sub of subComponents) {
    exportNames.push(sub.name)
  }
  sections.push(`export {\n  ${exportNames.join(",\n  ")},\n}`)

  return (
    "// Generated by shadcn Playground\n\n" +
    sections.join("\n\n") +
    "\n"
  )
}

/** Renders an ElementNode tree as indented JSX. */
function renderElementTree(
  node: ElementNode,
  indent: number,
  isRoot: boolean,
  dataSlot?: string,
): string {
  const pad = " ".repeat(indent * 2)
  const tag = node.tag
  const classStr = node.classes.length > 0 ? node.classes.join(" ") : ""
  const hasChildren = node.children.length > 0
  const hasText = node.text !== undefined && node.text.length > 0

  // Build attributes
  const attrs: string[] = []
  if (isRoot) {
    if (dataSlot) {
      attrs.push(`data-slot="${dataSlot}"`)
    }
    attrs.push("ref={ref}")
    if (classStr) {
      attrs.push(`className={cn("${classStr}", className)}`)
    } else {
      attrs.push("className={cn(className)}")
    }
    attrs.push("{...props}")
  } else if (classStr) {
    attrs.push(`className="${classStr}"`)
  }

  // HTML attributes from node.props
  if (node.props) {
    for (const [key, value] of Object.entries(node.props)) {
      attrs.push(`${key}="${value}"`)
    }
  }

  const attrStr = attrs.length > 0 ? " " + attrs.join(" ") : ""

  if (!hasChildren && !hasText) {
    // Self-closing for void elements or empty containers
    if (isRoot) {
      // Root always gets children pass-through
      return `${pad}<${tag}${attrStr}>\n${pad}  {children}\n${pad}</${tag}>`
    }
    return `${pad}<${tag}${attrStr} />`
  }

  const lines: string[] = []
  lines.push(`${pad}<${tag}${attrStr}>`)

  if (isRoot) {
    // If root has explicit children in tree, render them, otherwise pass children prop
    if (hasChildren) {
      for (const child of node.children) {
        lines.push(renderElementTree(child, indent + 1, false))
      }
    }
    if (hasText) {
      lines.push(`${pad}  ${node.text}`)
    }
    if (!hasChildren) {
      lines.push(`${pad}  {children}`)
    }
  } else {
    if (hasText) {
      lines.push(`${pad}  ${node.text}`)
    }
    for (const child of node.children) {
      lines.push(renderElementTree(child, indent + 1, false))
    }
  }

  lines.push(`${pad}</${tag}>`)
  return lines.join("\n")
}

/** Generates a sub-component as a separate forwardRef component. */
function generateSubComponent(
  sub: SubComponentDef,
  _parentName: string,
): string {
  const elementInfo = getElementTypeInfo(sub.baseElement)
  const hasVariants = sub.variants.length > 0
  const hasProps = sub.props.length > 0
  const variantsName = `${toCamelCase(sub.name)}Variants`

  // Inline type for sub-component
  const extraProps: string[] = []
  for (const v of sub.variants) {
    const unionType = v.type === "boolean"
      ? "boolean"
      : v.options.map((o) => `"${o}"`).join(" | ")
    extraProps.push(`${v.name}?: ${unionType}`)
  }
  for (const prop of sub.props) {
    const tsType = propTypeToTs(prop.type, false)
    const optional = prop.required ? "" : "?"
    extraProps.push(`${prop.name}${optional}: ${tsType}`)
  }

  const typeAnnotation = extraProps.length > 0
    ? `React.ComponentProps<"${sub.baseElement}"> & { ${extraProps.join("; ")} }`
    : `React.ComponentProps<"${sub.baseElement}">`

  // Destructured props (separate ...props from named props to avoid trailing comma)
  const subNamedProps = [
    "className",
    ...sub.variants.map((v) => {
      const def = v.defaultValue
      if (v.type === "boolean") return `${v.name} = ${def === "true" ? "true" : "false"}`
      return def ? `${v.name} = "${def}"` : v.name
    }),
    ...sub.props.map((p) => p.name),
  ]

  // Prepend convention classes (named group + heading font) so they sit
  // before user-applied classes in the className output.
  const conventionClasses: string[] = []
  if (sub.namedGroup) {
    const subKebab = sub.name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()
    conventionClasses.push(`group/${subKebab}`)
  }
  if (sub.headingFont) {
    conventionClasses.push("cn-font-heading")
  }

  const subBaseClasses = [...conventionClasses, ...(sub.classes ?? [])]
    .filter(Boolean)
    .join(" ")
  const classNameExpr = subBaseClasses
    ? `cn("${subBaseClasses}", className)`
    : "className"

  // Build data-* attributes for each variant prop
  const dataAttrs = sub.variants.map((v) => {
    const kebab = v.name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()
    return `data-${kebab}={${v.name}}`
  })

  const attrLines = [
    sub.dataSlot ? `data-slot="${sub.dataSlot}"` : "",
    ...dataAttrs,
    `className={${classNameExpr}}`,
    "{...props}",
  ].filter(Boolean)

  return `function ${sub.name}({ ${subNamedProps.join(", ")}, ...props }: ${typeAnnotation}) {
  return (
    <${sub.baseElement}
      ${attrLines.join("\n      ")}
    />
  )
}`
}

/** Converts a ComponentProp type to its TypeScript equivalent. */
function propTypeToTs(
  type: "string" | "number" | "boolean" | "ReactNode",
  _hasReactNode: boolean,
): string {
  switch (type) {
    case "string":
      return "string"
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "ReactNode":
      return "React.ReactNode"
  }
}

/** Formats a default value for destructuring based on prop type. */
function formatDefaultValue(prop: ComponentProp): string {
  if (prop.defaultValue === undefined || prop.defaultValue === "") return ""
  switch (prop.type) {
    case "string":
      return `"${prop.defaultValue}"`
    case "number":
      return prop.defaultValue
    case "boolean":
      return prop.defaultValue
    case "ReactNode":
      return "undefined"
  }
}

/* ── Shared helpers ────────────────────────────────────────────── */

/** Advances past a string literal, handling escape characters. */
function skipString(source: string, start: number, quote: string): number {
  let i = start + 1
  while (i < source.length) {
    if (source[i] === "\\" && quote !== "`") {
      i += 2
      continue
    }
    if (source[i] === quote) return i + 1
    i++
  }
  return i
}
