// Code Generator — produces a clean .tsx file from component state + edits
// Uses string-based injection at known patterns rather than full AST manipulation.

import type { CustomVariantDef } from "@/lib/component-state"

/* ── Public types ──────────────────────────────────────────────── */

export interface GenerateOptions {
  slug: string
  originalSource: string
  customClasses: Record<string, string[]>
  customVariantDefs: CustomVariantDef[]
  activeSubComponents: string[]
  componentName: string
}

/* ── Generator ─────────────────────────────────────────────────── */

/**
 * Takes the current component state (original source + edits) and produces
 * a clean .tsx string ready for export.
 *
 * If no edits have been made (no custom classes, no custom variants, and
 * all sub-components still active), the original source is returned with
 * only a header comment prepended.
 */
export function generateComponentCode(options: GenerateOptions): string {
  const {
    originalSource,
    customClasses,
    customVariantDefs,
    activeSubComponents,
    componentName,
  } = options

  const hasCustomClasses = Object.values(customClasses).some(
    (classes) => classes.length > 0,
  )
  const hasCustomVariants = customVariantDefs.length > 0
  const isUnmodified = !hasCustomClasses && !hasCustomVariants

  const header = `// Generated by shadcn Playground\n// Component: ${componentName}\n\n`

  if (isUnmodified) {
    return header + originalSource
  }

  let output = originalSource

  // ── Inject custom classes into the root className / cva base ───
  if (hasCustomClasses) {
    output = injectCustomClasses(output, customClasses)
  }

  // ── Inject custom variant definitions into cva variants block ──
  if (hasCustomVariants) {
    output = injectCustomVariants(output, customVariantDefs)
  }

  return header + output
}

/* ── Class injection ───────────────────────────────────────────── */

/**
 * Injects custom classes into the component source. For "root" classes,
 * appends them to the first cva() base string or the first cn() /
 * className occurrence.
 */
function injectCustomClasses(
  source: string,
  customClasses: Record<string, string[]>,
): string {
  let output = source

  // Handle "root" element classes
  const rootClasses = customClasses["root"]
  if (rootClasses && rootClasses.length > 0) {
    const classString = rootClasses.join(" ")

    // Strategy 1: Inject into cva() base string — cva("existing-classes",
    const cvaBaseMatch = /cva\(\s*"([^"]*)"/.exec(output)
    if (cvaBaseMatch) {
      const existingBase = cvaBaseMatch[1]
      const newBase = `${existingBase} ${classString}`
      output = output.replace(
        `cva("${existingBase}"`,
        `cva("${newBase}"`,
      )
      return output
    }

    // Strategy 2: Inject into the first cn() call inside a className
    const cnMatch = /className=\{cn\(\s*"([^"]*)"/.exec(output)
    if (cnMatch) {
      const existingCn = cnMatch[1]
      const newCn = `${existingCn} ${classString}`
      output = output.replace(
        `className={cn("${existingCn}"`,
        `className={cn("${newCn}"`,
      )
      return output
    }

    // Strategy 3: Inject into a plain className string
    const classNameMatch = /className="([^"]*)"/.exec(output)
    if (classNameMatch) {
      const existingClass = classNameMatch[1]
      const newClass = `${existingClass} ${classString}`
      output = output.replace(
        `className="${existingClass}"`,
        `className="${newClass}"`,
      )
    }
  }

  return output
}

/* ── Variant injection ─────────────────────────────────────────── */

/**
 * Injects custom variant definitions into the cva() variants block.
 * If a cva() call exists with a variants block, appends the new variants.
 * If cva() exists without a variants block, this is a no-op (rare case).
 */
function injectCustomVariants(
  source: string,
  customVariantDefs: CustomVariantDef[],
): string {
  let output = source

  // Find the variants block inside cva()
  const variantsBlockStart = findVariantsBlockEnd(output)
  if (variantsBlockStart === -1) {
    // No variants block found — try to create one inside cva()
    return injectVariantsBlock(output, customVariantDefs)
  }

  // Build the new variant entries
  const variantEntries = customVariantDefs
    .map((def) => formatVariantEntry(def))
    .join("")

  // Insert before the closing brace of the variants block
  output =
    output.slice(0, variantsBlockStart) +
    variantEntries +
    output.slice(variantsBlockStart)

  // Also inject into defaultVariants
  output = injectDefaultVariants(output, customVariantDefs)

  return output
}

/**
 * Finds the position just before the closing `}` of the `variants: { ... }`
 * block inside cva(). Returns -1 if not found.
 */
function findVariantsBlockEnd(source: string): number {
  const pattern = /variants\s*:\s*\{/
  const match = pattern.exec(source)
  if (!match) return -1

  const startIndex = match.index + match[0].length
  let depth = 1
  let i = startIndex

  while (i < source.length && depth > 0) {
    const char = source[i]
    if (char === "{") depth++
    else if (char === "}") depth--

    if (depth === 0) return i // position of the closing }

    // Skip string literals
    if (char === '"' || char === "'" || char === "`") {
      i = skipString(source, i, char)
      continue
    }

    i++
  }

  return -1
}

/**
 * Creates a full variants block inside an existing cva() call that
 * doesn't have one yet.
 */
function injectVariantsBlock(
  source: string,
  defs: CustomVariantDef[],
): string {
  // Find `cva("...",` or `cva("..."` and look for the config object
  const cvaMatch = /cva\(\s*"[^"]*"\s*,\s*\{/.exec(source)
  if (!cvaMatch) return source

  const insertPos = cvaMatch.index + cvaMatch[0].length
  const variantEntries = defs.map((def) => formatVariantEntry(def)).join("")

  const variantsBlock = `\n    variants: {${variantEntries}\n    },`

  return (
    source.slice(0, insertPos) + variantsBlock + source.slice(insertPos)
  )
}

/**
 * Injects default values for custom variants into the defaultVariants block.
 */
function injectDefaultVariants(
  source: string,
  defs: CustomVariantDef[],
): string {
  const defaultsPattern = /defaultVariants\s*:\s*\{/
  const match = defaultsPattern.exec(source)
  if (!match) return source

  const insertPos = match.index + match[0].length
  const defaults = defs
    .map((def) => `\n      ${def.name}: "${def.defaultValue}",`)
    .join("")

  return source.slice(0, insertPos) + defaults + source.slice(insertPos)
}

/**
 * Formats a single custom variant definition as a cva variants entry.
 */
function formatVariantEntry(def: CustomVariantDef): string {
  if (def.type === "boolean") {
    return `\n      ${def.name}: {\n        true: "",\n        false: "",\n      },`
  }

  const optionEntries = def.options
    .map((opt) => `\n          ${opt}: "",`)
    .join("")

  return `\n      ${def.name}: {${optionEntries}\n      },`
}

/* ── Shared helpers ────────────────────────────────────────────── */

/** Advances past a string literal, handling escape characters. */
function skipString(source: string, start: number, quote: string): number {
  let i = start + 1
  while (i < source.length) {
    if (source[i] === "\\" && quote !== "`") {
      i += 2
      continue
    }
    if (source[i] === quote) return i + 1
    i++
  }
  return i
}
